name: gestor_alunos
description: App Flutter de referência - Gestão de Alunos
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15

  cupertino_icons: ^1.0.5
  flutter_riverpod: ^2.3.6
  go_router: ^7.0.0
  dio: ^5.2.0
  flutter_secure_storage: ^9.0.0
  intl: ^0.18.0
  path_provider: ^2.0.14
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true  # ✅ ESSA LINHA ATIVA OS ÍCONES DO MATERIAL DESIGN

  assets:
    - assets/images/
